introduction/urls.py
from django.urls import path
from . import views

app_name="introduction"
urlpatterns = [
    path('', views.one, name="one"),
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name="main"),
    path('introduction/', include('introduction.urls')),
    path('posts/', include('posts.urls')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import new, create, main, show, update, delete

app_name = "posts"
urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('show/<int:id>', show, name="show"),
    path('update/<int:id>/', update, name="update"),
    path('delte/<int:id>/', delete, name = "delete"),
]

introduction/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
 
class Product(models.Model):
    item = models.CharField(max_length=50, null=False)
    explanation = models.TextField(null=False)
    price = models.IntegerField(null=False)
    stock = models.IntegerField(null=False)
    image = models.ImageField(upload_to = 'images/',null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null=True)


class Review(models.Model):
    raiting = models.IntegerField()
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Product, on_delete = models.CASCADE, related_name='comments')

introduction/views.py
from django.shortcuts import render

# Create your views here.
def one(request):
    return render(request, 'introduction/one.html')

myblog/views.py
from django.shortcuts import render


def main(request):
    return render(request, 'main.html')

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product
from .models import Review

# Create your views here.

def new(request):
    return render(request, 'posts/new.html')
    

def create(request):
    if request.method == "POST":
        item = request.POST.get('item')
        explanation = request.POST.get('explanation')
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        image = request.FILES.get('image')
        user = request.user
        Product.objects.create(item=item, explanation=explanation, price=price, stock=stock, image=image, user=user)
        return redirect('posts:main')


def main(request):
    posts = Product.objects.all()
    return render(request, 'posts/main.html', {'posts': posts})


def show(request, id):
    post = Product.objects.get(pk=id)
    post.save()
    return render(request, 'posts/show.html', {'post': post})


def update(request,id):
    post = get_object_or_404(Product,pk=id)
    if request.method == "POST":
        post.item = request.POST['item']
        post.explanation = request.POST['explanation']
        post.price = request.POST['price']
        post.stock = request.POST['stock']
        post.image = request.FILES.get('image') 
        post.save()
        return redirect('posts:show',post.id)
    return render(request, 'posts/update.html',{"post":post})


def delete(request,id):
    post = get_object_or_404(Product,pk=id)
    post.delete()
    return redirect("posts:main")

introduction/templates/introduction/one.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1> 군인 용품 쇼핑몰입니다.</h1>
{% endblock %}}

myblog/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/project.css' %}">
    <title>shopping mall</title>
  </head>
  <body>
    {% include 'shared/_navbar.html' %}
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

myblog/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <img src="{% static 'images/army.jpg' %}" style= "width: 50%;" class="img-fluid mx-auto d-block" alt="Responsive image">
{% endblock %}

myblog/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href='{% url "main" %}'>국군 쇼핑몰</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href='{% url "introduction:one" %}'>페이지 소개</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:new' %}">상품 등록</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:main' %}">상품 목록</a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right ">
        <li class="nav-item dropdown ">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">계정</a>
          <div class="dropdown-menu">
            {% if user.is_authenticated %}{# 유저가 로그인 중이면 #}
              <a class="dropdown-item" href="{% url 'account_logout' %}" class="nav-link">로그아웃</a>
              <a class="dropdown-item" href="{% url 'account_change_password' %}">비밀번호 변경</a>
            {% else %}
              <a class="dropdown-item" href="{% url 'account_login' %}" class="nav-link">로그인</a>
              <a class="dropdown-item" href="{% url 'account_signup' %}" class="nav-link">회원 가입</a>
            {% endif %}
          </div>
        </li>
      </ul>
    </div>
  </nav>

posts/templates/posts/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% if user.is_authenticated %} {#유저가 로그인한 상태라면 #}

        <div class="container2">
            <h1 style = "font-weight: bold; color: rgb(32, 84, 179);">상품 목록</h1>
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4 col-12">
                        <div class="card text-center" style="width: 18rem; margin-top: 20px;">
                            <div class="card-body">
                                <h5 class="card-title">{{ post.item }}</h5>
                                <p class="card-text">{{ post.explanation }}</p>
                                <p class="card-text">남은 수량: {{ post.stock }}개</p>
                                <p class="card-text">가격: {{ post.price }}원</p>                                
                                {% if post.image %}
                                    <br>
                                    <img src ="{{ post.image.url }}" style="height: 100px; width:70px;">
                                {%  endif %}
                                <br>
                                <a href="{% url 'posts:show' post.pk %}" class="btn btn-primary">자세히</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% else %}
        <h3> 로그인 후 이용이 가능합니다.</h3>
        <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
        <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
        {% endif %}
        {% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% if user.is_authenticated %} {#유저가 로그인한 상태라면 #}

        <div class="container1">
            <h1 style = "font-weight: bold; color: rgb(32, 84, 179);">상품 판매</h1>
            <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                <label>상품 이름</label>
                <input type="text" class="form-control" name="item">
                </div>
                <div class="form-group">
                <label>상품 설명</label>
                <input type="text" class="form-control" name="explanation">
                </div>
                <div class="form-group">
                <label>상품 가격</label>
                <input type="text" class="form-control" name="price">
                </div>
                <div class="form-group">
                <label>상품 재고</label>
                <input type="text" class="form-control" name="stock">
                </div>
                <input type="submit" value="글 작성" class="btn btn-outline-primary">
                <input type="file" name ="image">
            </form>
        </div>
    {% else %}
        <h3> 로그인 후 이용이 가능합니다.</h3>
        <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
        <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>
    {% endif %}
{% endblock %}

posts/templates/posts/show.html
{% extends 'base.html' %}
{% block content %}
<br><br><br><br>
<h2 style = "color: powderblue; font-weight: bold; text-align: center;">상세보기 페이지</h2>
<br><br><br><br>
    {% if post.image %}
        <br>
        <img src ="{{ post.image.url }}" style="height: 50%; width:50%; margin-left:auto; margin-right:auto; display: block;">
    {%  endif %}
<h5 style = "font-weight: bold;">상품명 : {{ post.item }} </h5><br>
{% if post.user %}
    <h5 style = "font-weight: bold;">판매자 : {{ post.user }} </h5><br>
{% else %}
    <h5 style = "font-weight: bold;">이름: 알 수 없음 </h5><br>
{% endif %}
<h5 style = "font-weight: bold;">상품 설명 : {{ post.explanation }} </h5><br>
<h5 style = "font-weight: bold;">상품 가격 : {{ post.price }}원 </h5><br>
<h5 style = "font-weight: bold;">남은 재고 : {{ post.stock }}개 </h5><br>
<h5 style = "font-weight: bold;">작성 시각 : {{ post.created_at }} </h5><br>
<h5 style = "font-weight: bold;">수정 시각 : {{ post.updated_at }} </h5><br>
<div class = "kmg123123" style = "text-align: center;"> 
    {% if user == post.user %}
        <a href = "{% url 'posts:update' post.pk %}" class="btn btn-primary">수정하기</a>
        <a href = "{% url 'posts:delete' post.pk %}" class="btn btn-danger">삭제하기</a>
    {% else %}  
    {% endif %}
</div>
{% endblock %}

posts/templates/posts/update.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 style = "font-weight: bold; color: rgb(32, 84, 179);">
        수정하기
    </h1>
    <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
    <label>상품명</label>
    <input type="text" class="form-control" name="item" value= "{{post.item}}">
    </div>
    <div class="form-group">
    <label>상품 설명</label>
    <textarea class="form-control" name="explanation">{{post.explanation}}</textarea>
    </div>
    <div class="form-group">
    <label>상품 가격</label>
    <input type="text" class="form-control" name="price" value= "{{post.price}}">
    </div>
    <div class="form-group">
    <label>상품 재고</label>
    <input type="text" class="form-control" name="stock" value= "{{post.stock}}">
    </div>  
    <input type="submit" value="글 수정" class="btn btn-outline-primary">
    <input type="file" name ="image">
    </form>
</div>
{% endblock %}